package michal.dto.mapper;

import michal.dto.ItemsImageDTO;
import michal.entity.ItemsImageEntity;
import michal.entity.enumy.ImageType;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.web.multipart.MultipartFile;

/**
 * MapStruct mapper for converting uploaded image data into {@link ItemsImageEntity}
 * and for converting {@link ItemsImageEntity} into {@link ItemsImageDTO}.
 *
 * <p>
 * The upload mapping intentionally ignores fields that must be generated by the application
 * (e.g. database ID, stored file name, timestamps, and entity relations).
 * </p>
 */
@Mapper(componentModel = "spring")
public interface ItemsImageMapper {

    /**
     * Creates a new {@link ItemsImageEntity} based on an uploaded file and detected image type.
     *
     * <p>
     * The method maps only metadata that can be derived directly from the uploaded file
     * (size, original filename) and from server-side validation (content type).
     * Fields such as ID, storedName, createdAt and the item relation are ignored because they
     * are set later in the service layer.
     * </p>
     *
     * @param file uploaded multipart file (image)
     * @param imageType validated/normalized image type (e.g. PNG, JPEG)
     * @return new entity instance with mapped metadata
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "storedName", ignore = true)
    @Mapping(target = "item", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "size", source = "file.size")
    @Mapping(target = "originalName", source = "file.originalFilename")
    @Mapping(target = "contentType", source = "imageType")
    ItemsImageEntity fromUpload(MultipartFile file, ImageType imageType);

    /**
     * Converts an image entity to a DTO used by the API.
     *
     * <p>
     * Additionally maps the related item ID to a flat DTO field (itemsId),
     * which is useful on the frontend without exposing the whole item entity.
     * </p>
     *
     * @param source image entity
     * @return DTO representation of the image
     */
    @Mapping(target = "itemsId", source = "item.id")
    ItemsImageDTO toDTO(ItemsImageEntity source);
}
