package michal.dto.mapper;

import michal.dto.ListDTO;
import michal.dto.SharedListDTO;
import michal.entity.ListEntity;
import michal.entity.SharedListEntity;
import michal.entity.UserEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for converting between {@link SharedListEntity} and {@link SharedListDTO}.
 *
 * <p>
 * This mapper is responsible for handling the association entity that represents
 * a shared list between a list owner and another user.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface SharedListMapper {

    /**
     * Creates a new {@link SharedListEntity} from an existing list and user.
     *
     * <p>
     * This method is typically used when sharing a list with another user.
     * The identifier is ignored because it is generated by the database.
     * </p>
     *
     * @param list list that is being shared
     * @param user user with whom the list is shared
     * @return new shared list entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "list", source = "list")
    @Mapping(target = "user", source = "user")
    SharedListEntity toEntity(ListEntity list, UserEntity user);

    /**
     * Converts a {@link SharedListEntity} into a {@link SharedListDTO}.
     *
     * <p>
     * Flattens nested relations so the frontend can easily display
     * information about the shared user and the related list.
     * </p>
     *
     * @param entity shared list entity
     * @return DTO representation of the shared list
     */
    @Mapping(target = "email", source = "user.email")
    @Mapping(target = "userId", source = "user.id")
    @Mapping(target = "listId", source = "list.id")
    SharedListDTO toDTO(SharedListEntity entity);
}
