spring:
  datasource:
    url: jdbc:postgresql://localhost/ShoppingList
    username: postgres
    password: fortment
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true


server:
  port: ${PORT:8080}
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false


springdoc:
  api-docs.path: /api-docs




