package michal.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import michal.entity.enumy.ImageType;
import java.time.LocalDate;

/**
 * Entity representing an image associated with a single item.
 *
 * <p>
 * This entity stores metadata about an uploaded image,
 * such as its original name, size and creation date.
 * The actual file is typically stored outside the database
 * (e.g. on disk or cloud storage).
 * </p>
 */
@Entity(name = "image")
@Getter
@Setter
public class ItemsImageEntity {

    /**
     * Primary key of the image entity.
     *
     * <p>
     * The ID is generated automatically using a database sequence.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "images_seq")
    @SequenceGenerator(name = "images_seq", sequenceName = "images_seq", allocationSize = 1)
    private Long id;

    /**
     * Internal filename used when storing the image on disk.
     *
     * <p>
     * This name is usually generated by the application
     * (e.g. UUID or timestamp-based) to avoid filename collisions.
     * It does not have to match the original uploaded filename.
     * </p>
     */
    @Column
    private String storedName;

    /**
     * Type of the image content.
     *
     * <p>
     * This value is stored as a String representation of {@link ImageType}
     * in the database (e.g. PNG, JPEG).
     * It is used to validate supported image formats
     * and to determine how the image should be handled.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column
    private ImageType contentType;

    /**
     * Original filename as uploaded by the user.
     */
    @Column
    private String originalName;

    /**
     * Reference to the item this image belongs to.
     *
     * <p>
     * This is a one-to-one relationship:
     * one item can have at most one image.
     * </p>
     */
    @OneToOne
    @JoinColumn(name = "item_id", unique = true, nullable = false)
    private ItemsEntity item;

    /**
     * Date when the image was created or uploaded.
     */
    @Column
    private LocalDate createdAt;

    /**
     * Size of the image file in bytes.
     */
    @Column
    private Long size;
}
